# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_pb2 as model__pb2


class SearchStub(object):
    """Define the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getSimilarTopicsFor = channel.unary_unary(
                '/Search/getSimilarTopicsFor',
                request_serializer=model__pb2.Features.SerializeToString,
                response_deserializer=model__pb2.Result.FromString,
                )


class SearchServicer(object):
    """Define the service
    """

    def getSimilarTopicsFor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getSimilarTopicsFor': grpc.unary_unary_rpc_method_handler(
                    servicer.getSimilarTopicsFor,
                    request_deserializer=model__pb2.Features.FromString,
                    response_serializer=model__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Search', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Search(object):
    """Define the service
    """

    @staticmethod
    def getSimilarTopicsFor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Search/getSimilarTopicsFor',
            model__pb2.Features.SerializeToString,
            model__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
