name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
<<<<<<< HEAD
    - name: Setup Docker tag and label names
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ghcr.io/kentyou/sensinact-tls
        tag-sha: ${{ steps.extract_branch.outputs.branch == 'main' }}
        tag-edge: true
        tag-semver: |
          {{version}}
          {{major}}.{{minor}}
          {{major}}
    - name: AI4EU Registry
=======
    - name: GitHub Container Registry Login
>>>>>>> 92c1969c33f62f35f68892fc0e202eeaa6599f4c
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' || startsWith( github.ref, 'refs/tags/' ) }}
        tags: ghcr.io/kentyou/ai4eu-ke4wot:latest
